/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "Join the Discord!": "加入 Discord!",
    "Background on/off": "背景 开/关",
    "Beginner": "新手",
    "already discovered)": "已经发现的)",
    "Chests have a double chance of": "宝箱有双倍概率",
    "clicker": "点击器",
    "Close": "关闭",
    "Collect all XP": "收集所有经验值",
    "Common potions": "普通药水",
    "Hard reset": "硬重置",
    "Level": "等级",
    "Hover over a potion to learn about it!": "悬停在药水上了解它！",
    "Next button unlocks at level": "下一个按钮解锁于等级",
    "Next chest unlocks at level": "下一个宝箱解锁于等级",
    "Open common chest": "打开普通宝箱",
    "Potions opened:": "打开药水次数：",
    "Time played:": "游戏时长:",
    "producing their corresponding rarity": "生成对应的稀有度",
    "total XP multiplier from potions": "从药水中获得的总经验乘数",
    "View potions": "查看药水",
    "XP to next level:": "经验值到达下一级:",
    "Basic": "基础",
    "Bulbous": "球状的",
    "common": "普通",
    "Gained a triangular": "获得一个三角形",
    "Large": "大的",
    "Massive": "巨大的",
    "potion": "药水",
    "potion!": "药水!",
    "rare": "稀有",
    "Rare potions": "稀有药水",
    "Rotund": "矮胖",
    "Round": "圆形",
    "Tall round": "高圆",
    "Tall triangular": "高三角形",
    "Tall wide": "高宽",
    "Tiny": "微小的",
    "Triangular": "三角形",
    "uncommon": "罕见",
    "Uncommon potions": "罕见药水",
    "Wide": "宽的",
    "Average": "平均",
    "Brilliant": "辉煌",
    "Competent": "主管",
    "epic": "史诗",
    "Celestial potions": "天体药水",
    "Mythical potions": "神话药水",
    "Epic potions": "史诗药水",
    "Exceptional": "异常",
    "Expert": "专家",
    "Extraordinary": "非凡",
    "Gained a basic": "获得一个基础",
    "Gained a bulbous": "获得一个球状",
    "Gained a rotund": "获得了一个矮胖",
    "Gained a tall round": "获得一个高圆的",
    "Gained a large": "获得一个大的",
    "Gained a massive": "获得一个巨大的",
    "Gained a tall wide": "获得一个高宽",
    "Gained a round": "获得一个圆形",
    "Gained a tall triangular": "获得一个高三角形",
    "Gained a tiny": "获得了一个微小的",
    "Gained a wide": "获得一个宽的",
    "Legendary": "传说",
    "legendary": "传说",
    "Legendary potions": "传说药水",
    "Master": "大师",
    "Mediocre": "平庸",
    "Open celestial chest": "开启天体宝箱",
    "Open epic chest": "开启史诗宝箱",
    "Open mythical chest": "打开神话宝箱",
    "Open legendary chest": "打开传说宝箱",
    "Open rare chest": "打开罕见宝箱",
    "Open uncommon chest": "打开罕见宝箱",
    "Proficient": "精通",
    "Renowned": "大名鼎鼎",
    "Respectable": "受人尊敬的",
    "Skilled": "熟练的",
    "Talented": "才华横溢的",
    "Unremarkable": "不起眼的",
    "Extreme": "极品",
    "Insane": "疯狂",
    "mythical": "神话",
    "Mythical": "神话",
    "Superior": "上品",
    "Supreme": "至尊",
    "Unmatched": "无与伦比",
    "Immortal": "不朽的",
    "celestial": "天体",
    "Celestial": "天体",
    "Cosmic": "宇宙",
    "Demonic": "恶魔",
    "Eternal": "永恒的",
    "Galactic": "银河",
    "Godly": "敬神",
    "Incomprehensible": "不可理解的",
    "Infinite": "无限",
    "Infinity": "无限",
    "Multiversal": "多元宇宙",
    "Omnipotent": "全能的",
    "Omniversal": "万能的",
    "Open void chest": "打开虚空宝箱",
    "Transcendent": "卓越的",
    "Universal": "通用",
    "void": "虚空",
    "Void potions": "虚空药水",
    "Voidborn": "虚空出生",
    "· Pet Crates": "· 宠物宝箱",
    "· Pets": "· 宠物",
    "· Token Buttons": "· 代币按钮",
    "· XP Buttons": "· 经验按钮",
    "· XPBoost Buttons": "· 经验提升按钮",
    "beginner clicker": "新手点击器",
    "COLLECTIONS": "收藏",
    "Dark": "深色",
    "Daily rewards": "日常奖励",
    "Daily reward": "日常奖励",
    "Current selected pet:": "当前选择的宠物:",
    "Theme:": "主题:",
    "Stats": "统计",
    "Red": "红色",
    "Rainbow": "彩虹色",
    "Purple": "紫色",
    "Pets": "宠物",
    "On": "开",
    "Neon": "霓虹",
    "Midnight": "午夜",
    "Manual save": "手动保存",
    "Light": "浅色",
    "MAIN BUTTONS": "主要按钮",
    "Help": "帮助",
    "Hard\n                    reset": "硬重置",
    "Green": "绿色",
    "Gityx游戏": "Gityx游戏",
    "Display stats": "显示统计",
    "Apprentice Clicker": "学徒点击者",
    "Check Back Reclocked": "再次点击查看",
    "Claim rewards by clicking first button. Others are for buying upgrades": "点击第一个按钮领取奖励，其余按钮用于购买升级",
    "Click on a pet you've unlocked to equip it": "点击已解锁的宠物进行装备",
    "Click on an icon to watch related statistics": "点击图标查看相关统计",
    "Click on any pet to equip it": "点击任意宠物进行装备",
    "Inverted": "反转色",
    "Unbox a random basicpet": "开箱：随机获得一只基础宠物",
    "Unbox a random commonpet": "开箱：随机获得一只普通宠物",
    "Unbox a random earthpet": "开箱：随机获得一只大地宠物",
    "Unbox a random firepet": "开箱：随机获得一只火焰宠物",
    "Unbox a random skeletonpet": "开箱：随机获得一只骷髅宠物",
    "Unboxed Pets": "开箱宠物",
    "Volcano": "火山色",
    "Challenger Clicker": "挑战者点击器",
    "Green Spider": "绿蜘蛛",
    "Green Lizard": "绿蜥蜴",
    "Rat": "老鼠",
    "Slug": "蛞蝓",
    "Green Butterfly": "绿蝴蝶",
    "Green Dragon": "绿龙",
    "A rat forced to eat trash to survive. It'd love to eat a fresh slug anyday.": "一只老鼠被迫靠吃垃圾来维持生存。它其实非常想随时吃到新鲜的蜗牛呢。",
    "A snail that lost its shell and has to live underneath a bridge... for now.": "一只失去了外壳、不得不住在桥下的蜗牛……目前而言。",
    "Effects:": "效果：",
    "Green butterflies are known to be annoying when crossing forests.": "绿色的蝴蝶在穿过森林时往往会令人感到恼火。",
    "Myths say that this dragon is a symbol of luck. Do they drink liquid luck?": "传说中称这种龙是幸运的象征。它们会饮用幸运之液吗？",
    "Rapid bug that cammouflages through green environments.": "这种快速移动的昆虫能够在绿色环境中伪装自己。",
    "Timeskip": "跳过时间",
    "Cost:": "成本:",
    "Effect:": "效果:",
    "Grants XP based on 1st button amount and increases XP gain": "根据第一个按钮的数值发放经验值，并增加经验值获取量",
    "Instant XP": "即时经验值",
    "Liquid Luck": "液体运气",
    "One time x1.5 crate luck and +5% luck": "一次性获得 1.5 倍的箱子运气值以及 +5% 的运气值",
    "Skips a certain amount of time to the future. Cost resets when claiming daily rewards": "跳过一段时间，前往未来。在领取每日奖励时，消耗值会重置。",
    "Rarities for this crate:": "这个箱子的稀有度：",
    "💀 Open a skeleton crate 💀": "💀 打开一个骷髅宝箱 💀",
    "💠 Open a basic crate 💠": "💠 打开一个基础宝箱 💠",
    "🔥 Open a fire crate 🔥": "🔥 打开一个火焰宝箱 🔥",
    "🦂 Open a earth crate 🦂": "🦂 打开一个大地宝箱 🦂",
    "🦎 Open a nature crate 🦎": "🦎 打开一个自然宝箱 🦎",
    "Snake": "蛇",
    "Green SalamSpiderander": "绿蜘蛛",
    "Green Salamander": "绿蝾螈",
    "A snake living in barren wastes, looking for any juicy rat to eat.": "一条蛇栖息在荒芜的荒野之中，四处寻找鲜嫩的啮齿动物来吞食。",
    "Their only danger comes from accidentally touching them.": "它们面临的唯一威胁来自于意外触碰到它们。",
    "Small Elf": "小精灵",
    "They live on leaves because they can't make cobwebs.": "它们靠吃树叶为生，因为它们不会织网。",
    "This breed of elves is so small that they cannot harvest anything bigger than a mushroom. They love to dine on snakes.": "这种精灵体型非常小，以至于他们连比蘑菇还大的东西都无法采摘。他们最喜欢的食物是蛇。",
    "(Pixelgrab)": "（Pixelgrab）",
    "Alderi: Helpful css changes": "Alderi：有用的css更改",
    "All testers and everyone who played, including you <3": "所有测试人员以及所有参与游戏的玩家，包括您 <3",
    "Collection completionist progress:": "收集完成主义的进度：",
    "Credits": "鸣谢",
    "Demonin:": "Demonin:",
    "Dungeon Crawl:": "地下城探险：",
    "Luck factors:": "幸运因素：",
    "Many textures are open-source and come from this project": "许多纹理是开源的，来自本项目",
    "Mirakos: Clock icon": "Mirakos：时钟图标",
    "Original Check Back": "原版 常回来看看",
    "Pet Stats": "宠物统计",
    "Player stats": "玩家统计",
    "XP Cooldown modifiers:": "经验值冷却修正值：",
    "XP Multipliers:": "经验值乘数：",
    "XP Stats": "经验值统计",
    "Green Crocodile": "绿鳄鱼",
    "It has a little button that makes it say 'See ya later, alligator'.": "它有一个小按钮，按下后就会显示“再见啦，鳄鱼”。",
    "Turtle": "乌龟",
    "Not the fastest sheriff of the wild west.": "并非是西部荒野中最快的警长。",
    "An australian nightmare if it weren't for their big green eyes.": "如果不是因为那双大大的绿色眼睛，这简直就是澳大利亚人的噩梦。",
    "Do I know the green butterfly? I'd rather not know her.": "我认识那只绿色的蝴蝶吗？我宁愿不知道她的存在。",
    "Purple Butterfly": "紫蝴蝶",
    "Tarantula": "狼蛛",
    "1-Headed Snake": "单头蛇",
    "Earth Snake": "土蛇",
    "Scorpion": "蝎子",
    "People used to call me the 'Death Scorpion' but I prefer being a farmer, so I dropped the name.": "过去人们都叫我“死亡蝎子”，但我更愿意做一名农民，所以我就不再使用这个称呼了。",
    "Unlike other snakes, this one saw the Avatar training, and learned a thing or two about earth bending.": "与其他蛇类不同，这只蛇目睹了阿凡达的训练过程，并从中学到了一些关于土力操控的知识。",
    "Where are the other heads? They were lost in a crazy blackjack night. Maybe this snake will restore them eventually.": "其他那些脑袋都去哪儿了？它们在疯狂的“二黑”之夜中失踪了。也许这条蛇最终会把它们找回来。",
    "Earth Dragon": "土龙",
    "The father of the Earth, this dragon can make life out of sticks and stones.": "这位大地之父，这只巨龙能够将木头和石头变成生命之物。",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "idea": "创意",
    "false": "否",
    "true": "是",
    "Alpha": "正式版",
    "(Creator: MarcElAcoplao,": "(作者: MarcElAcoplao,",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "(": "(",
    ")": ")",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",
    'Twitter': 'Twitter',
    "Discord": "Discord",
    "Facebook": "Facebook",
    "Instagram": "Instagram",
    "gityxcom": "gityxcom",
    "Footer": "Footer",
    "Wiki": "Wiki",
    "gityx": "gityx",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'II',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    'Jan': '1月',
    'Feb': '2月',
    'Mar': '3月',
    'Apr': '4月',
    'May': '5月',
    'Jun': '6月',
    'Jul': '7月',
    'Aug': '8月',
    'Sep': '9月',
    'Oct': '10月',
    'Nov': '11月',
    'Dec': '12月',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
//例如：Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头："Coin: ":"金币: "
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": " ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "Check Back: The Infinite Descent v": "常回来看看：无限下降 v",
    "Already discovered - ": "已发现 - ",
    "Crate emojis: ": "箱子表情包: ",
    "XP Multi: x": "经验乘数: x",
    "You will unlock something new at level ": "你将解锁一些新东西在等级 ",
    "XP to next level: ": "到下一级还需经验值: ",
    "Cooldowns: ": "冷却时间: ",
    "XP Gain: ": "经验增益: ",
    "Time skipped: ": "跳过时间: ",
    "Multiplier: ": "乘数: ",
    "Green Lizard: ": "绿蜥蜴: ",
    "Green Salamander: ": "绿蝾螈: ",
    "Green Spider: ": "绿蜘蛛: ",
    "Green Dragon: ": "绿龙: ",
    "Green Crocodile: ": "绿鳄鱼: ",
    "Green Butterfly: ": "绿蝴蝶: ",
    "Rat: ": "老鼠: ",
    "Small Elf: ": "小精灵: ",
    "Snake: ": "蛇: ",
    "Slug: ": "蛞蝓: ",
    "Highest level: ": "最高等级: ",
    "Pets owned: ": "拥有的宠物: ",
    "Nature crate: ": "自然宝箱: ",
    "Button clicks: ": "按钮点击数: ",
    "Basic crate: ": "基础宝箱: ",
    "Crates opened: ": "打开的宝箱: ",
    "TOTAL: ": "总计: ",
    "Unlocks: ": "解锁: ",
    "Time played: : ": "游戏时长: ",
    "Turtle: ": "乌龟: ",
    "Tarantula: ": "狼蛛: ",
    "Cat: ": "猫: ",
    "1-Headed Snake: ": "单头蛇: ",
    "Earth Dragon: ": "土龙: ",
    "Earth Snake: ": "土蛇: ",
    "Scorpion: ": "蝎子: ",
    "Purple Butterfly: ": "紫蝴蝶: ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如：13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾：" Coin":" 金币"
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "/sec)": "/秒)",
    ' I': ' I',
    ' II': ' II',
    ' III': ' III',
    ' IV': ' IV',
    ' V': ' V',
    ' VI': ' VI',
    ' VII': ' VII',
    ' VIII': ' VIII',
    ' X': ' X',
    ' XI': ' XI',
    ' XII': ' XII',
    ' XIII': ' XIII',
    ' XIV': ' XIV',
    ' XV': ' XV',
    ' XVI': ' XVI',
    "/level": "/等级",
    " XP Cooldowns": " 经验冷却",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)h$/,
    /^([\d\.]+)m$/,
    /^([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.]+)\xa0(.+)$/,
    /^([\d\.]+)\xa0(.+)\/([\d\.]+)\xa0(.+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+) Sp$/,
    /^([\d\.]+) Oc$/,
    /^([\d\.]+) Dc$/,
    /^([\d\.]+) UDc$/,
    /^([\d\.]+) No$/,
    /^([\d\.]+) Sx$/,
    /^([\d\.]+) QaDc$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^\/([\d\.]+)$/,
    /^\+([\d\.]+)\%$/,
    /^([\d\.]+) \+([\d\.]+)\%$/,
    /^([\d\.,]+)$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])|[\u21A9\u21AA\u25B6\u25C0\u2B06\u2B07\u2B05\u2B95\u2B99\u2B9A]+$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])+$/,
    // /^[\uD800-\uFFFF]+$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//字母加数字：([\d\.]+[A-Za-z])
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
//&nbsp;空格：\xA0
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Check back in (.+)$/, '请在 $1 后回来'],
    [/^Check Back in (.+)$/, '请在 $1 后回来'],
    [/^Gain (.+) XP$/, '获取 $1 经验值'],
    [/^You have (.+) luck charges$/, '你有 $1 幸运充能'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^(.+) of (.+) discovered \- (.+) XP gain$/, '$1 \/ $2 一发现 - $3 经验 增益'],
    [/^Jan ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 1 月 $1, $3:$4'],
    [/^Feb ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 2 月 $1, $3:$4'],
    [/^Mar ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 3 月 $1, $3:$4'],
    [/^Apr ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 4 月 $1, $3:$4'],
    [/^May ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 5 月 $1, $3:$4'],
    [/^Jun ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 6 月 $1, $3:$4'],
    [/^Jul ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 7 月 $1, $3:$4'],
    [/^Aug ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 8 月 $1, $3:$4'],
    [/^Sep ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 9 月 $1, $3:$4'],
    [/^Oct ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 10 月 $1, $3:$4'],
    [/^Nov ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 11 月 $1, $3:$4'],
    [/^Dec ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 12 月 $1, $3:$4'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^x([\d\.]+) XP gain$/, 'x$1 经验值增益'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^You have ([\d\.,]+)$/, '你有 $1'],
    [/^x([\d\.]+) XP$/, 'x$1 经验值'],
    [/^x([\d\.]+) from pets$/, 'x$1 来自宠物'],
    [/^x([\d\.]+) from daily rewards$/, 'x$1 来自日常奖励'],
    [/^x([\d\.]+) Luck will be used$/, 'x$1 幸运将被使用'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^([\d\.,]+)m ([\d\.,]+)s$/, '$1 分 $2 秒'],
    [/^([\d\.,]+)h ([\d\.,]+)m$/, '$1 小时 $2 分'],
    [/^([\d\.,]+)h ([\d\.,]+)s$/, '$1 小时 $2 秒'],
    [/^([\d\.,]+) of ([\d\.,]+) discovered \-$/, '$1 \/ $2 已发现 -'],
    [/^([\d\.,]+) in ([\d\.,]+)$/, '$1 \/ $2'],
    [/^([\d\.,]+) in ([\d\.,]+)!!$/, '$1 \/ $2!!'],
    [/^Upgrade ([\d\.,]+)$/, '升级 $1'],
    [/^Gain ([\d\.]+)XPBoost$/, '获得 $1 经验值提升'],
    [/^Gain ([\d\.,]+) XPBoost$/, '获得 $1 经验值提升'],
    [/^Gain ([\d\.,]+) Token$/, '获得 $1 代币'],
    [/^Gain ([\d\.,]+) Daily tokens$/, '获得 $1 日常代币'],
    [/^Get ([\d\.,]+) unlocks$/, '获得 $1 解锁'],
    [/^Level ([\d\.,]+)$/, '等级 $1'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^level ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^level: ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);